-- Generated manually for bootstrap; prefer `prisma migrate dev` to regenerate.
CREATE TABLE IF NOT EXISTS "User" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT UNIQUE NOT NULL, "phone" TEXT, "city" TEXT, "marketingConsent" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Child" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "name" TEXT, "age" INTEGER NOT NULL, "grade" TEXT, "gender" TEXT);
CREATE TABLE IF NOT EXISTS "Order" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "amount" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'RUB', "status" TEXT NOT NULL DEFAULT 'pending', "provider" TEXT NOT NULL, "providerPaymentId" TEXT, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "paidAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "TestSession" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "childId" TEXT REFERENCES "Child"("id"), "token" TEXT UNIQUE NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "status" TEXT NOT NULL DEFAULT 'active', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Question" ("id" TEXT PRIMARY KEY, "externalId" TEXT, "text" TEXT NOT NULL, "orderIndex" INTEGER NOT NULL, "answerType" TEXT NOT NULL, "options" JSONB NOT NULL, "mappingKey" TEXT);
CREATE TABLE IF NOT EXISTS "Answer" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "TestSession"("id"), "questionId" TEXT NOT NULL REFERENCES "Question"("id"), "value" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("sessionId","questionId"));
CREATE TABLE IF NOT EXISTS "Result" ("id" TEXT PRIMARY KEY, "sessionId" TEXT UNIQUE NOT NULL REFERENCES "TestSession"("id"), "primaryIntelligence" TEXT NOT NULL, "secondaryIntelligence" TEXT NOT NULL, "scoresJson" JSONB NOT NULL, "emailedAt" TIMESTAMP, "status" TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS "WebhookLog" ("id" TEXT PRIMARY KEY, "provider" TEXT NOT NULL, "event" TEXT NOT NULL, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
